version: 2
updates:
  # Frontend dependencies (React + Vite)
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "react"
        versions: ["18.x.x"]

  # Backend dependencies (Node.js)
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "weekly"

  # Docker dependencies for frontend
  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "weekly"

  # Docker dependencies for backend
  - package-ecosystem: "docker"
    directory: "/backend"
    schedule:
      interval: "weekly"
      
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
