version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8080

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - database
    environment:
      - DATABASE_URL=jdbc:postgresql://database:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres

  database:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres