services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    env_file:
      - ./frontend/.env

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    depends_on:
      - pgvector
    env_file:
      - ./backend/.env

  pgvector:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    env_file:
      - ./database/.env
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
